gem_build_task:
  container:
    matrix:
      - image: ruby:2.6
      - image: ruby:latest
  auto_cancellation: true
  use_compute_credits: $CIRRUS_PR == ''
  env:
    JEKYLL_ENV: production
    NOKOGIRI_USE_SYSTEM_LIBRARIES: false
  bootstrap_script: gem install bundler
  bundler_cache:
    folder: /usr/local/bundle
    fingerprint_script: cat Gemfile
    populate_script: bundler
  build_script: bundler exec rake --trace --verbose
  gem_artifacts:
    path: ./*.gem
  only_if: $CIRRUS_BRANCH != "images"
