gem_build_task:
  container:
    image: ruby:$RUBY_VERSION
  auto_cancellation: true
  use_compute_credits: $CIRRUS_PR == ''
  env:
    JEKYLL_ENV: production
    NOKOGIRI_USE_SYSTEM_LIBRARIES: false
    matrix:
      - RUBY_VERSION: latest
      - RUBY_VERSION: 2.6
  bootstrap_script: gem install bundler
  bundler_cache:
    folder: /usr/local/bundle
    fingerprint_script: cat Gemfile
    populate_script: bundler
  build_script: bundler exec rake --trace --verbose
  gem_artifacts:
    path: ./*.gem
