gem_build_task:
  container:
    image: ruby:latest
  env:
    JEKYLL_ENV: production
  bootstrap_script: |
    gem update --system
    gem update
    gem install bundler
  install_dependencies_script: bundle install
  build_script: bundle exec rake --trace --verbose
  gem_artifacts:
    path: ./*.gem

tests_task:
  container:
    image: rdilpickle/better-wsfull:latest
  env:
    JEKYLL_ENV: production
  Yarn_cache:
    folder: testSite/node_modules
    populate_script: cd testSite && yarn install
    fingerprint_script: cd testSite && cat package.json && cat yarn.lock
  install_ruby_dependencies_script: source "$HOME/.rvm/scripts/rvm" && bundle install
  clone_bulma_script: cd _sass && git clone https://github.com/jgthms/bulma.git && cd bulma && git checkout 0dc4416
  run_tests_script: cd testSite && source "$HOME/.rvm/scripts/rvm" && yarn test
