gem_build_task:
  container:
    image: ruby:latest
  env:
    JEKYLL_ENV: production
  bootstrap_script: |
    gem update --system
    gem install bundler
  install_dependencies_script: bundle install
  build_script: bundle exec rake --trace --verbose
  gem_artifacts:
    path: ./*.gem
