gem_build_task:
  container:
    image: ruby:latest
  auto_cancellation: true
  use_compute_credits: $CIRRUS_PR == ''
  env:
    JEKYLL_ENV: production
    NOKOGIRI_USE_SYSTEM_LIBRARIES: false
  bootstrap_script: |
    gem update --system
    gem update
    gem install bundler
  bundler_cache:
    folder: /usr/local/bundle
  install_dependencies_script: bundle install
  build_script: bundle exec rake --trace --verbose
  gem_artifacts:
    path: ./*.gem
