theme: picklecore
name: PickleCore Test Site
title: Example

# you can edit this stuff though if testing:
github: rdilweb
port: 3000
description: This is a cool example site
url: https://example.com
skin: light
